### ISSUE TITLE
load.sh: 48: printf: Illegal option -v

### ISSUE THREAD

**Issue by dac514** [elastic/packetbeat-dashboards#17]
On Ubuntu 14.04 running

`./load.sh http://localhost:9200`

Gives the following error(s):

```
Loading dashboard Topbeat-Dashboard:
{"_index":".kibana","_type":"dashboard","_id":"Topbeat-Dashboard","_version":1,"created":true}
./load.sh: 48: printf: Illegal option -v
Loading index pattern :
No handler found for uri [/.kibana/index-pattern/] and method [PUT]
./load.sh: 48: printf: Illegal option -v
```

First line should probably be: #!/bin/bash. 

@see http://stackoverflow.com/questions/28302474/shellscript-throws-errors-but-somehow-is-still-working

Workaround:

`bash ./load.sh http://localhost:9200`

**Comment by andrewkroh** [comment]
Thanks for reporting this.
