### ISSUE TITLE
Update index patterns to use wildcard

### ISSUE THREAD

**Issue by reedloden** [elastic/packetbeat-dashboards#36]
As per https://github.com/elastic/kibana/issues/4342, <beat>-\* is the new hotness. Need to update all the index patterns shipped with the dashboard to use wildcard index patterns rather than the old time-based naming convention.

**Comment by lmangani** [comment]
fixing a few array issues, will update PR

**Comment by reedloden** [comment]
This is now fixed. Thanks!
