### ISSUE TITLE
Powershell script to load the Kibana dashboards in Elasticsearch

### ISSUE THREAD

**Issue by monicasarbu** [elastic/packetbeat-dashboards#44]
Currently, we offer a bash script load.sh to load the Kibana dashboards in Elasticsearch. It would be nice to have a script for the Windows users as well.

**Comment by dedemorton** [comment]
A PowerShell script might be best because we already ask users to install PowerShell for installing on Windows.

**Comment by dedemorton** [comment]
+1

**Comment by monicasarbu** [comment]
done in https://github.com/elastic/beats-dashboards/pull/57
