### ISSUE TITLE
-url option missing from usage examples in load.sh

### ISSUE THREAD

**Issue by dedemorton** [elastic/packetbeat-dashboards#52]
@monicasarbu Minor issue: shouldn't the usage notes in load.sh include the -url parameter? Or does it also work without the parameter? 

Usage examples:
env KIBANA_INDEX='.kibana_env1' ./load.sh
./load.sh http://test.com:9200
./load.sh http://test.com:9200 test

**Comment by monicasarbu** [comment]
@dedemorton It works without any parameter as well and it uses the ES on localhost:9200 and .kibana index to insert the dashboards.

<pre>
 ~/src/github.com/elastic/beats-dashboards [master|✔] $ ./load.sh -h
  Load the dashboards, visualizations and index patterns into the given Elasticsearch instance.
Usage:
  ./load.sh -url http://localhost:9200 -user admin -index .kibana_env1
Options:
  -h | -help
    Print the help menu.
  -l | -url
    Elasticseacrh URL. By default is http://localhost:9200.
  -u | -user
    Username to connect to Elasticsearch. By default no username is used.
  -i | -index
    Kibana index pattern where to save the dashboards, visualizations, index patterns. By default is .kibana.
</pre>

I think it would be nice to add this output to the docs, so people can see that they can also choose the index pattern where to store the Kibana dashboards.

**Comment by dedemorton** [comment]
@monicasarbu I've changed the note in the doc to say, "If Elasticsearch is not running on 127.0.0.1:9200, you need to specify the Elasticsearch location as an argument to the load.sh command. For example: ./load.sh -url http://192.168.33.60:9200. Use the -help option to see other available options." Do you think that is good enough? Or do you want me to specifically mention that you can specify an index pattern? We just have to remember that too much detail in a getting started topic is not a good idea.

**Comment by monicasarbu** [comment]
@dedemorton It's enough to just explain about -url option, but I will just print the output of the load.sh -help for people to see more details.

**Comment by monicasarbu** [comment]
@dedemorton I think it makes sense to move this issue to libbeat as it applies to docs

**Comment by dedemorton** [comment]
PR https://github.com/elastic/beats/pull/847 adds info about the load commands to the doc, so I'm closing this issue now. I show the -url option in the example because it makes it more explicit that the script needs to know the location of Elastisearch (unless it's running on localhost).
