### ISSUE TITLE
{"error":"NullPointerException[null]","status":500}

### ISSUE THREAD

**Issue by lauid** [elastic/packetbeat-dashboards#55]
[root@localhost:packetbeat-dashboards]#./load.sh -url http://localhost:9200
Loading dashboards to http://localhost:9200 in .kibana using curl:
Loading search Cache-transactions:
{"error":"NullPointerException[null]","status":500}
Loading search DB-transactions:
{"error":"NullPointerException[null]","status":500}
Loading search Default-Search:
{"error":"NullPointerException[null]","status":500}
Loading search Errors:
{"error":"NullPointerException[null]","status":500}
Loading search Filesystem-stats:
{"error":"NullPointerException[null]","status":500}
Loading search HTTP-errors:
{"error":"NullPointerException[null]","status":500}
Loading search MongoDB-errors:
{"error":"NullPointerException[null]","status":500}
Loading search MongoDB-transactions:
{"error":"NullPointerException[null]","status":500}
Loading search MongoDB-transactions-with-write-concern-0:
{"error":"NullPointerException[null]","status":500}
Loading search MySQL-errors:
{"error":"NullPointerException[null]","status":500}
Loading search MySQL-Transactions:
{"error":"NullPointerException[null]","status":500}

why?
how to solve ?

**Comment by monicasarbu** [comment]
The load.sh script is using the `curl` command to load the searches, visualizations and dashboards in Elasticsearch, so this error is returned by the `curl` command when adding to Elasticsearch.

You can try to spot for more errors that are printed out by Elasticsearch and maybe check that the curl command is working properly with simple queries:

<pre>
 curl -XGET 'http://localhost:9200/.kibana/search/Cache-transactions?pretty'
 curl -XGET 'http://localhost:9200/.kibana/pretty'
</pre>
