### ISSUE TITLE
Document Kibana version compatibility for new releases

### ISSUE THREAD

**Issue by andrewkroh** [elastic/packetbeat-dashboards#72]
We should document that versions of Kibana that each beats-dashboards release was tested against.

**Comment by andrewkroh** [comment]
Based on discussions on Slack, we believe the dashboards are compatible with all versions of Kibana 4, so one option is to just add a statement saying, "The beats dashboard require Kibana 4."

If we want to be more specific we could list the exact versions that we tested against when we made the release. Something like, "The beats dashboards need Kibana 4 and were tested with Kibana 4.1.2 and Kibana 4.3.0".

I think we should start with the first option, and if in the future we find problems with compatibility then we can change the statement to call out specific versions.

**Comment by monicasarbu** [comment]
Fixed by #860
