### ISSUE TITLE
load.sh fails in master

### ISSUE THREAD

**Issue by monicasarbu** [elastic/packetbeat-dashboards#73]
load.sh fails to load in master. Here are the logs: 

Loading dashboard Winlogbeat-Dashboard:
{"_index":".kibana","_type":"dashboard","_id":"Winlogbeat-Dashboard","_version":4,"created":false}
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
Loading index pattern :
No handler found for uri [/.kibana/index-pattern/] and method [PUT]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
Loading index pattern :
No handler found for uri [/.kibana/index-pattern/] and method [PUT]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
Loading index pattern :
No handler found for uri [/.kibana/index-pattern/] and method [PUT]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
Loading index pattern :
No handler found for uri [/.kibana/index-pattern/] and method [PUT]

**Comment by monicasarbu** [comment]
@andrewkroh It looks to me that the load.sh fails when loading the Winlogbeat dashboard (only in master). Can you please try it on your laptop to see if it works for you? Maybe you forgot to push some files. Thanks

**Comment by monicasarbu** [comment]
An error is raised as the default version `grep` doesn't support the `-P` option, so I replaced the command with `awk`. Here is the fix: https://github.com/elastic/beats-dashboards/pull/76

**Comment by monicasarbu** [comment]
The bug appears in v1.1.0, so we need to backport the fix to 1.1.0 as well.

**Comment by monicasarbu** [comment]
@andrewkroh can you please test again to see if the load script works as expected on windows? Thanks!

**Comment by andrewkroh** [comment]
I have been using RHEL lately so I didn't notice this problem because it has the `-P` option. I will retest `load.sh` and `load.ps1` on master and 1.1. today

**Comment by andrewkroh** [comment]
I tested on OSX and Windows using both master and 1.1. LGTM
