### ISSUE TITLE
Unanalyzed Index for beats.hostname?

### ISSUE THREAD

**Issue by chuckyz** [elastic/packetbeat-dashboards#74]
Hello,

I heavily utilize AWS which leaves me with hostnames like ip-172-31-10-10, these then are analyzed as "ip", "172", "31", ...

Would it be acceptable for me to add in an additional unanalyzed field e.g.: `beats.hostname-unanalyzed`?

**Comment by andrewkroh** [comment]
Install the provided template to Elasticsearch first and the string will not be analyzed. See the [Getting Started](https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-getting-started.html#packetbeat-template) guide.
