### ISSUE TITLE
Variable 'name' in script is in lowercase in load.sh

### ISSUE THREAD

**Issue by radoondas** [elastic/packetbeat-dashboards#82]
Hi,
this would be really small update of the script. Since all of the variables are uppercase, I think it would be logical to rename also this one.

```
name=`basename $file .json`
```

I have changed it already in my fork, I can create PR if needed.

**Comment by ruflin** [comment]
For the reference, PR is already here: https://github.com/elastic/beats-dashboards/pull/83

**Comment by radoondas** [comment]
This can be closed. It was resolved by PR #86
